### ISSUE TITLE
Provide an alternative, non-base64 encoded method+passwd URL for clients that don't support it (e.g. gost)

### ISSUE THREAD

**Issue by garoto** [Snawoot/nth-dump#1]
AFAICT, [gost](https://github.com/ginuerzh/gost/) only supports either `ss://<IP>:<PORT>?auth=<BASE64-ENCODED-METHOD+PASSWD>` or the standard `ss://<METHOD>:<PASS>@<IP>:<PORT>` scheme.

Generating an alternative `URL:` output can be a good thing perhaps? What do you think?

I'm using `gost` latest _official_ released binary for win64 (`gost 2.11.2 (go1.18 windows/amd64`), and a search for `base64` in the repo didn't returned any commits with that keyword anywhere, so I'm assuming support for this scheme doesn't exist.

**Comment by Snawoot** [comment]
Hi! Makes sense to make a command line option to control which URL format is used both for URL string and QR. Don't want to add all variants into output to not make it confusing.

**Comment by Snawoot** [comment]
Released in 1.1.0.

**Comment by garoto** [comment]
Working fine, cheers!
