### ISSUE TITLE
Can't find proxy servers

### ISSUE THREAD

**Issue by ve3xone** [Snawoot/nth-dump#8]
NTH-DUMP: 2022/09/01 16:09:25.894167 client.go:63: trying URL: "https://www.24c220f706df.info/getserver-190831.php?appVersion=5.1.0&id=52d4bee6-3419-4b3e-8b2f-a7b16315a643&key=Cxgh48fDSJhiWpk9&lang=en-US"
NTH-DUMP: 2022/09/01 16:09:26.651835 client.go:63: trying URL: "https://www.24c220f706df.info/getserver-190831.php?appVersion=5.1.0&id=52d4bee6-3419-4b3e-8b2f-a7b16315a643&key=Cxgh48fDSJhiWpk9&lang=en-US"
NTH-DUMP: 2022/09/01 16:09:26.836767 client.go:63: trying URL: "https://www.24c220f706df.info/getserver-190831.php?appVersion=5.1.0&id=52d4bee6-3419-4b3e-8b2f-a7b16315a643&key=Cxgh48fDSJhiWpk9&lang=en-US"
NTH-DUMP: 2022/09/01 16:09:27.041833 client.go:63: trying URL: "https://s3.us-west-1.amazonaws.com/nthassets/getserver.a"
NTH-DUMP: 2022/09/01 16:09:28.023199 client.go:78: getEncryptedBody(): errors occured: 3 errors occurred:
        * bad status code from API: code = 403, body = "Access Denied. This action has been logged for security review."
        * bad status code from API: code = 403, body = "Access Denied. This action has been logged for security review."
        * bad status code from API: code = 403, body = "Access Denied. This action has been logged for security review."

----------

Name:           nthLink Server
Host:           138.68.40.189
Port:           443
Method:         chacha20-ietf-poly1305
Password:       AFhgmOJPzhAI
URL:            ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpBRmhnbU9KUHpoQUk=@138.68.40.189:443#nthLink%20Server

----------

Gives one non-working server

**Comment by Snawoot** [comment]
Hi!

nthLink is doing their best to ban this app. Seems they're not very fond of actual opensource. Try following:

* Upgrade to latest version (1.5.0 at this moment).
* Try to change profiles (see `-profile` option).
* Try other IP addresses (seems like you've sent a lot of requests and they don't like you anymore).

Note that you may use http or socks proxy for this app, specifying `HTTPS_PROXY` environment variable. Description of format: https://pkg.go.dev/net/http#ProxyFromEnvironment

Here's one working for you, just in case - just tested it:

```
Name:		nthLink Server
Host:		142.93.162.50
Port:		443
Method:		chacha20-ietf-poly1305
Password:	q6cXA6Xce8dr
URL:		ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpxNmNYQTZYY2U4ZHI=@142.93.162.50:443#nthLink%20Server
```

That's all I can help you with.

**Comment by andruska** [comment]
> Name:\t\tnthLink Server\nHost:\t\t142.93.162.50\nPort:\t\t443\nMethod:\t\tchacha20-ietf-poly1305\nPassword:\tq6cXA6Xce8dr\nURL:\t\tss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpxNmNYQTZYY2U4ZHI=@142.93.162.50:443#nthLink%20Server\n

Hello !

Any configurations that nth-dump outputs will only live for a few hours. After that, for example, Shadoswocks for Android connects, but there is no internet. Does nthLink somehow rotate servers? Perhaps their security lies in the fact that their public credentials live for a short time and the nthLink app automatically uses (rotates) new servers after a certain period of time.

**Comment by Snawoot** [comment]
@andruska Hi! likely so. I can't tell exact period of time because I observe it same way as you.
